---
title: "Final Project Implmentation - Bayesian Model"
author: "Elizabeth Lattanzi"
date: "2025-11-30"
output: html_document
---

### Load necessary libraries 

```{r setup, include=FALSE}
library(sf)
library(dplyr)
library(readr)
library(ggplot2)
library(brms)
library(loo)
library(janitor)
library(stringr)
library(lubridate)
library(purrr)
library(bayesplot)
library(Metrics)
```


### Read in the data 

```{r}

data <- read.csv("bayesian_data.csv")

```


### Fit Bayesian model

```{r}


bayes_model_pm25 <- brm(
  formula = incidence_numeric ~ pm25_avg_z * log_burned_acres + urban_rural,
  data = data,
  family = gaussian(),
  prior = c(set_prior("normal(2, 3)", class = "b"), set_prior("student_t(3, 0, 10)", class = "sigma")),
  seed = 15,
  chains = 5,
  iter = 5000,
  warmup = 1000,
  control = list(adapt_delta = 0.95))



```

### Evaluate model

```{r}

summary(bayes_model_pm25)
pp_check(bayes_model_pm25)
loo(bayes_model_pm25)

```



### Posterior prediction

```{r}


bayes_data_pred <- data %>%
  filter(!is.na(log_burned_acres), !is.na(urban_rural), !is.na(incidence_numeric), !is.na(pm25_avg_z))

fitted_values <- fitted(bayes_model_pm25, newdata = bayes_data_pred)
bayes_data_pred$predicted_mean <- fitted_values[, "Estimate"]
bayes_data_pred$predicted_lower <- fitted_values[, "Q2.5"]
bayes_data_pred$predicted_upper <- fitted_values[, "Q97.5"]


```

### Print Summary Statistics

```{r}



bayes_data_pred$residuals <- bayes_data_pred$incidence_numeric - bayes_data_pred$predicted_mean
mae_val <- mae(bayes_data_pred$incidence_numeric, bayes_data_pred$predicted_mean)
r2_val <- bayes_R2(bayes_model_pm25)
r2_summary <- summary(r2_val)
confidence_95 <- with(bayes_data_pred, incidence_numeric >= predicted_lower & incidence_numeric <= predicted_upper)
coverage_rate <- mean(confidence_95, na.rm = TRUE)
print(r2_summary)

cat("Final Model Performance Summary\n")
cat(sprintf("MAE (Mean Absolute Error): %.2f\n", mae_val))
cat(sprintf("Bayesian R²: %.2f\n", r2_val))




```


### Plot Bayesian Regression 

```{r}



ggplot(new_data, aes(x = y_incidence, y = y_pred)) +
  geom_point(color = "blue") +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "darkgray") +
  labs(
    title = "Observed vs. Predicted Lung Cancer Incidence",
    x = "Observed Incidence",
    y = "Predicted Incidence"
  ) +
  theme_minimal()


```